### ISSUE TITLE
Output filenames

### ISSUE THREAD

**Issue by hereismyname** [SSW-DataLab/Policies#20]
Wanting to create some guidelines for generating separate files.
Ideally, one should avoid creating multiple files, but we occasionally generate files for visualization software & modeling etc. 

As policy, recommend appending these designations into filenames:
`-e- `: 'extract'-- indicates that this is a file that should be read and used by analytic code. Variable construction has been completed, and the data can be considered tidy, aside from specific needs for the analyst in setting up whatever analysis they are planning on running (e.g. changing the names of factor levels, minor changes, etc.).

`-a-`: 'analytic'-- this represents a file that was used for data analysis. It should only vary slightly from it's -e- counterpart, e.g. certain factor levels have been collapsed due to cell-size, or other small modifications took place. It should accompany analytic code, and can be used for in-house replication.

`-o-`: 'output'-- this represents a file that contains results, or output. Sometimes we need to store numbers/values prior to their conversion to tables in manuscripts. This designation should indicate this purpose.

**Comment by ClaytonJY** [comment]
I'm against these short abbreviation; I don't think there's any harm in being verbose, but using non-standard abbreviations specific to our lab adds cognitive load to our analysts and will confuse external contributors.

I also don't see the need for the `output` label, and the extract/analytic divide seems pretty tenuous. I can appreciate the need for better file organization/labeling, but I think this solution adds more trouble than it's worth. Let's discuss other options. What issues have arisen that you think would be solved with the above policies, @hereismyname?

**Comment by hereismyname** [comment]
@ClaytonJY 

As I mentioned above, my preference would be to avoid creating separate files, but we've experienced segmentation in our workflow, and not all of our work is done in a single environment (i.e. R). If we were using a more "pure" workflow, we'd largely be able to avoid supplemental/secondary files, but that isn't an option. I'm also okay with verbose file names, but my goal is to introduce some standardization on how we identify specific files.

For example, each of these files don't necessarily intuit their purpose, unless one is the author of their name:
```
stability-first.csv/Rds
stability-full.csv/Rds
stability-demographics.csv/Rds
stability-analytic-frame.csv/Rds
stability-final-df.csv/Rds
```

It's difficult to tell which of these is the base data-file, and which might be used for analysis. I agree that the difference between extract/analytic file seems tenuous, but we have a good example with our stability project, in which a paper is directly using a sub-sample from a previously created file. 

I'm not meaning to pick on any individuals who've contributed to the names-- they've largely taken their names from what the objects are called in the working markdown that produced them. This is generally fine, but requires the person to be familiar with each step in the markdown code that produces each file (again, ideally there should only be _one_ step, but this may not always be the case). Being fully up to speed on a markdown file and knowing some shorthand on file-names are both problems of cognitive load. Additionally, some members e.g. Christian Vasquez may be more involved with product preparation (e.g. table construction), but not analysis, and just need to know which files they should be directed to.

My suggested format (`~/directory/project-filetype-filedesc`) is a way to make sure that certain files cluster together when sorted in a file-explorer/GUI. 

I anticipate that we will be producing at least three file types in the future:
  - extracts, representing completed samples & finalized measurement construction; 
  - analytic files, representing any final tuning, level-collapsing, paper-specific filtering; and 
  - output, representing files formatted efficiently for table construction and visualization

These could be placed separately in sub-directories, but this also seems undesirable.

**Comment by beperron** [comment]
We can solve a big part of this problem by creating an XLS file of the
csv.  I can do this on my own -- Tableau reads XLS with multiple sheets, so
this is an ideal solution for my needs.  The RDS for these are just
duplicates of the csv.

On Wed, Mar 23, 2016 at 10:19 AM, Andrew Moore <notifications@github.com>
wrote:

> @ClaytonJY <https://github.com/ClaytonJY>
>
> As I mentioned above, my preference would be to avoid creating separate
> files, but we've experienced segmentation in our workflow, and not all of
> our work is done in a single environment (i.e. R). If we were using a more
> "pure" workflow, we'd largely be able to avoid supplemental/secondary
> files, but that isn't an option. I'm also okay with verbose file names, but
> my goal is to introduce some standardization on how we identify specific
> files.
>
> For example, each of these files don't necessarily intuit their purpose,
> unless one is the author of their name:
>
> stability-first.csv/Rds
> stability-full.csv/Rds
> stability-demographics.csv/Rds
> stability-analytic-frame.csv/Rds
> stability-final-df.csv/Rds
>
> It's difficult to tell which of these is the base data-file, and which
> might be used for analysis. I agree that the difference between
> extract/analytic file seems tenuous, but we have a good example with our
> stability project, in which a paper is directly using a sub-sample from a
> previously created file.
>
> I'm not meaning to pick on any individuals who've contributed to the
> names-- they've largely taken their names from what the objects are called
> in the working markdown that produced them. This is generally fine, but
> requires the person to be familiar with each step in the markdown code that
> produces each file (again, ideally there should only be *one* step, but
> this may not always be the case). Being fully up to speed on a markdown
> file and knowing some shorthand on file-names are both problems of
> cognitive load. Additionally, some members e.g. Christian Vasquez may be
> more involved with product preparation (e.g. table construction), but not
> analysis, and just need to know which files they should be directed to.
>
> My suggested format (~/directory/project-filetype-filedesc) is a way to
> make sure that certain files cluster together when sorted in a
> file-explorer/GUI.
>
> I anticipate that we will be producing at least three file types in the
> future:
>
>    - extracts, representing completed samples & finalized measurement
>    construction;
>    - analytic files, representing any final tuning, level-collapsing,
>    paper-specific filtering; and
>    - output, representing files formatted efficiently for table
>    construction and visualization
>
> These could be placed separately in sub-directories, but this also seems
> undesirable.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SSW-DataLab/Policies/issues/20#issuecomment-200364177>
>



-- 
Brian Perron, Ph.D.
Associate Professor
University of Michigan, School of Social Work

**Comment by hereismyname** [comment]
```
data(mtcars)
library(xlsx)

df1 <- mtcars[1:8, ]
df2 <- mtcars[9:20, ]

write.xlsx(df1, file = "test.xlsx", sheetName = "first-sheet")
write.xlsx(df2, file = "test.xlsx", sheetName = "second-sheet", append = TRUE)
```

I'd experienced some bugs with the xlsx package in the past, but I'm not able to reproduce them, which is good, because it means we have an immediate solution for the issue of files dedicated for visualization & model output. 

This may not be the proper place to resolve this issue, but some kind of standardization around how we organize file-names might be useful for the styleguide.
